name: "NodeJS"

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build"
        shell: bash
        
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Test"
        shell: bash  